[package]
name = "aoe-data"
version = "0.1.0"
authors = ["Simon <simon@systemli.org>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
structopt = "0.3"
